Repository Fan-Tion/Front-End, pull requests merged in 2024-07, with the labels that each got.

#3 초기 라이브러리 세팅 작업 했습니다.
  package.json
  src/App.css
  src/App.tsx
  src/api/axios.ts
  src/index.css
  src/layout/RootLayout.tsx
  src/main.tsx
  src/page/ErrorPage.tsx
  src/page/HomePage.tsx
  src/recoil/atoms/sampleAtoms.ts
  src/recoil/selectors/sampleSelector.ts
  src/routes/Routes.tsx
  yarn.lock
Labels: enhancement

#7 [PR] Jinyeong #4 detail page create
  src/components/DetailPageComponents/AuctionInfoModule.tsx
  src/components/DetailPageComponents/ImageModule.tsx
  src/components/DetailPageComponents/ItemDescription.tsx
  src/components/DetailPageComponents/SameKeywordAuctions.tsx
  src/components/DetailPageComponents/SellerRating.tsx
  src/components/DetailPageComponents/SteamedButton.tsx
  src/components/DetailPageComponents/index.tsx
  src/page/DetailPage.tsx
Labels: enhancement

#8 회원가입,로그인 페이지, 레이아웃, 페이지 구성했습니다.
  src/layout/LayoutFooter.tsx
  src/layout/LayoutHeader.tsx
  src/layout/RootLayout.tsx
  src/page/FindPasswordPage.tsx
  src/page/SignInPage.tsx
  src/page/SignUpPage.tsx
  src/routes/Routes.tsx
  src/styled-components/AuthStyle.ts
Labels: enhancement

#9 홈 페이지 뷰 생성
  src/components/HomePageComponent/AllProducts.tsx
  src/components/HomePageComponent/Category.tsx
  src/components/HomePageComponent/PopularCategory.tsx
  src/components/HomePageComponent/Product.tsx
  src/components/HomePageComponent/RecentlyViewedProducts.tsx
  src/components/HomePageComponent/index.tsx
  src/page/HomePage.tsx
  src/styled-components/HomePageStyle.ts
Labels: enhancement

#16 Jinyeong/14 msw setup
  .eslintrc.cjs
  package.json
  public/mockServiceWorker.js
  src/api/axios.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/page/SignInPage.tsx
  src/page/SignUpPage.tsx
  yarn.lock
Labels: enhancement, good first issue

#22 fix, feat : #19 mocked api creating request + #20 code convention calibration
  .eslintrc.cjs
  .gitignore
  .vscode/settings.json
  package.json
  public/mockServiceWorker.js
  public/vite.svg
  src/App.tsx
  src/api/auction.ts
  src/api/axios.ts
  src/api/member.ts
  src/components/DetailPageComponents/AuctionInfoModule.tsx
  src/components/DetailPageComponents/ImageModule.tsx
  src/components/DetailPageComponents/ItemDescription.tsx
  src/components/DetailPageComponents/SameKeywordAuctions.tsx
  src/components/DetailPageComponents/SellerRating.tsx
  src/components/DetailPageComponents/SteamedButton.tsx
  src/components/DetailPageComponents/index.tsx
  src/components/HomePageComponent/AllProducts.tsx
  src/components/HomePageComponent/Category.tsx
  src/components/HomePageComponent/PopularCategory.tsx
  src/components/HomePageComponent/Product.tsx
  src/components/HomePageComponent/RecentlyViewedProducts.tsx
  src/components/HomePageComponent/index.tsx
  src/components/MyPageComponent/HistoryView.tsx
  src/components/MyPageComponent/Profile.tsx
  src/components/MyPageComponent/SideProfile.tsx
  src/components/MyPageComponent/index.tsx
  src/components/PascalCase.tsx
  src/components/ProtectedRoute.tsx
  src/components/PublicRoute.tsx
  src/layout/LayoutFooter.tsx
  src/layout/LayoutHeader.tsx
  src/layout/RootLayout.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/db.ts
  src/mocks/handlers.ts
  src/page/DetailPage.tsx
  src/page/ErrorPage.tsx
  src/page/FindPasswordPage.tsx
  src/page/HomePage.tsx
  src/page/MyPage.tsx
  src/page/SignInPage.tsx
  src/page/SignUpPage.tsx
  src/routes/Routes.tsx
  src/styled-components/AuthStyle.ts
  yarn.lock
Labels: bug, enhancement

#24 Auction Create Page Develop
  package.json
  public/mockServiceWorker.js
  src/components/AuctionCreatePageComponents/DraggableFile.tsx
  src/components/AuctionCreatePageComponents/ImageUploader.tsx
  src/components/AuctionCreatePageComponents/InputArea.tsx
  src/components/AuctionCreatePageComponents/index.tsx
  src/mocks/handlers.ts
  src/page/AuctionCreatePage.tsx
  src/routes/Routes.tsx
  src/utils/TextEditor.tsx
  yarn.lock
Labels: enhancement, help wanted

#28 경매, 예치금 내역 페이지 생성
  src/api/history.ts
  src/components/AuctionHistoryPageComponents/AuctionHistoryContent.tsx
  src/components/AuctionHistoryPageComponents/Deposit.tsx
  src/components/AuctionHistoryPageComponents/WishList.tsx
  src/components/AuctionHistoryPageComponents/index.tsx
  src/components/DepositHistoryPageComponents/DepositHistoryContent.tsx
  src/components/DepositHistoryPageComponents/index.tsx
  src/components/MyPageComponent/HistoryView.tsx
  src/mocks/db.ts
  src/mocks/handlers.ts
  src/page/AuctionHistoryPage.tsx
  src/page/DepositHistoryPage.tsx
  src/routes/Routes.tsx
Labels: enhancement

#37 chore : 린트 설정과 프리티어 설정을 업데이트
  .eslintrc.cjs
  .vscode/settings.json
  package.json
  yarn.lock
Labels: enhancement

#51 re build detail page & Code split, API Connecting
  .gitignore
  .vscode/settings.json
  package.json
  src/api/auction.ts
  src/api/axios.ts
  src/components/AuctionCreatePageComponents/InputArea.tsx
  src/components/AuctionCreatePageComponents/index.tsx
  src/components/DetailPageComponents/AuctionInfoModule.tsx
  src/components/DetailPageComponents/ImageModule.tsx
  src/components/DetailPageComponents/ItemDescription.tsx
  src/components/DetailPageComponents/SellerRating.tsx
  src/components/DetailPageComponents/SteamedButton.tsx
  src/components/DetailPageComponents/atom/AuctionInfoModule.tsx
  src/components/DetailPageComponents/atom/ImageModule.tsx
  src/components/DetailPageComponents/atom/ItemDescription.tsx
  src/components/DetailPageComponents/atom/SameKeywordAuctions.tsx
  src/components/DetailPageComponents/atom/SellerRating.tsx
  src/components/DetailPageComponents/atom/SteamedButton.tsx
  src/components/DetailPageComponents/atom/index.ts
  src/components/DetailPageComponents/index.tsx
  src/hooks/useDateRange.ts
  src/hooks/useFileHandler.ts
  src/hooks/useFormHandler.ts
  src/hooks/useModalHandler.ts
  src/hooks/useStarRender.ts
  src/layout/LayoutHeader.tsx
  src/main.tsx
  src/mocks/db.ts
  src/mocks/handlers.ts
  src/pages/AuctionCreatePage.tsx
  src/pages/AuctionHistoryPage.tsx
  src/pages/DepositHistoryPage.tsx
  src/pages/DetailPage.tsx
  src/pages/ErrorPage.tsx
  src/pages/FindPasswordPage.tsx
  src/pages/HomePage.tsx
  src/pages/MyPage.tsx
  src/pages/PasswordResetPage.tsx
  src/pages/SignInPage.tsx
  src/pages/SignUpPage.tsx
  src/pages/index.tsx
  src/routes/Routes.tsx
  src/utils/TimeUtils.ts
  src/utils/fetchAuctionDetails.ts
  tsconfig.app.json
  vercel.json
  vite.config.ts
  yarn.lock
Labels: enhancement

#52 feat : Trade 모달 추가
  src/components/AuctionHistoryPageComponents/Deposit.tsx
  src/components/DepositRechargeComponent/CheckOut.tsx
  src/components/DepositRechargeComponent/Fail.tsx
  src/components/DepositRechargeComponent/Success.tsx
  src/components/MyPageComponent/SideProfile.tsx
  src/components/SignUpComponent/index.tsx
  src/components/TradeComponent/TradeDetail.tsx
  src/components/TradeComponent/TradeHistory.tsx
  src/mocks/handlers.ts
  src/pages/FailPage.tsx
  src/pages/SuccessPage.tsx
  src/pages/index.tsx
  src/routes/Routes.tsx
Labels: enhancement

#60 Jinyeong/59 api connect func fix
  .vscode/settings.json
  src/api/auction.ts
  src/api/axios.ts
  src/components/AuctionCreatePageComponents/InputArea.tsx
  src/components/AuctionCreatePageComponents/index.tsx
  src/components/DetailPageComponents/atom/AuctionInfoModule.tsx
  src/hooks/useFileHandler.ts
  src/hooks/useFormHandler.ts
  src/utils/TimeUtils.ts
Labels: wontfix

#68 상세 페이지 세부 기능 추가 건
  src/api/auction.ts
  src/components/AuctionCreatePageComponents/InputArea.tsx
  src/components/AuctionCreatePageComponents/index.tsx
  src/components/BidComponents/BidNow.tsx
  src/components/BidComponents/BuyNow.tsx
  src/components/BidComponents/index.ts
  src/components/DetailPageComponents/atom/AuctionInfoModule.tsx
  src/components/DetailPageComponents/atom/BidingHistory.tsx
  src/components/DetailPageComponents/atom/ImageModule.tsx
  src/components/DetailPageComponents/atom/SameKeywordAuctions.tsx
  src/components/DetailPageComponents/atom/SteamedButton.tsx
  src/components/DetailPageComponents/atom/index.ts
  src/components/DetailPageComponents/index.tsx
  src/constants/category.ts
  src/hooks/useModalHandler.ts
  src/mocks/db.ts
  src/utils/fetchAuctionDetails.ts
  tsconfig.app.json
  vite.config.ts
Labels: enhancement
